version: '3.8'
services:
  clean-arch-api:
    container_name: clean-arch-api
    entrypoint: sh -c 'yarn && yarn start:debug'
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app/
      - /app/node_modules/
    ports:
      - ${PORT}:${PORT}
      - ${PORT_DEBUG}:${PORT_DEBUG}
    networks:
      - clean-arch-net
    depends_on:
      - clean-arch-mongodb

  clean-arch-mongodb:
    image: mongo:latest
    container_name: clean-arch-mongodb
    environment:
      MONGODB_URI: ${MONGODB_URI}
    volumes:
      - mongodb-data/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - clean-arch-net

networks:
  clean-arch-net:

volumes:
  mongodb-data:
